.TH "epaper_conf_t" 3 "Sat Mar 10 2018" "esp-epaper-29-dke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
epaper_conf_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBreset_pin\fP"
.br
.ti -1c
.RI "int \fBdc_pin\fP"
.br
.ti -1c
.RI "int \fBcs_pin\fP"
.br
.ti -1c
.RI "int \fBbusy_pin\fP"
.br
.ti -1c
.RI "int \fBmosi_pin\fP"
.br
.ti -1c
.RI "int \fBmiso_pin\fP"
.br
.ti -1c
.RI "int \fBsck_pin\fP"
.br
.ti -1c
.RI "uint8_t \fBrst_active_level\fP"
.br
.ti -1c
.RI "uint8_t \fBbusy_active_level\fP"
.br
.ti -1c
.RI "uint8_t \fBdc_lev_data\fP"
.br
.ti -1c
.RI "uint8_t \fBdc_lev_cmd\fP"
.br
.ti -1c
.RI "int \fBclk_freq_hz\fP"
.br
.ti -1c
.RI "spi_host_device_t \fBspi_host\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "bool \fBcolor_inv\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for esp-epaper-29-dke from the source code\&.
