.TH "epaper_font_t" 3 "Sat Mar 10 2018" "esp-epaper-29-dke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
epaper_font_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBheight\fP"
.br
.ti -1c
.RI "const uint8_t * \fBfont_table\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for esp-epaper-29-dke from the source code\&.
